[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --chip esp32"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --chip esp32c3"

[env]
ESP_IDF_VERSION = "v5.3"

[alias]
build-devkit = "build --target xtensa-esp32-espidf --no-default-features --features esp32"
build-supermini = "build --target riscv32imc-esp-espidf --no-default-features --features esp32c3"

run-devkit = "run --target xtensa-esp32-espidf --no-default-features --features esp32"
run-supermini = "run --target riscv32imc-esp-espidf --no-default-features --features esp32c3"
